### DISCUSSION TITLE
Structure value validation

### DISCUSSION THREAD

**Discussion by dariada** [cuelang/cue#392] [General]
Hey, I have a ConfigMap file that contains a data block of string and number variables.
Is there a way to to check that the value meets certain conditions but does not limit the field name?

For example,
For fields that are string check that they contain quotes at the beginning and end without referring to the field name itself so we can add new fields without describing each one.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment
  namespace: backend
data:
  NAME_SEPARATOR: "_"
  DB_HOST: some_string
  POSTRESQL_HOST: some_string
  POSTRESQL_PORT: "5432"
  MYSQL_PORT: "3306"
  REDIS_PORT: "6379"
  ENV_NAME: "staging"
  LOG_FORMAT: "json"
```
