### DISCUSSION TITLE
Validate conditional fields

### DISCUSSION THREAD

**Discussion by ostcar** [cuelang/cue#706] [Q&A] [answered]
I have a list of structs. Dependent on the value of one field the structs have different other fields.

For example here is a yml file with two persons. Minors need someone responsible:
```yml
---
person1:
  name: Bob
  age: 35

person2:
  name: Bill
  age: 12
  responsible: Anna
```

I am trying to validate this with this schema:

```cue
person1: #Person
person2: #Person

#Person: {
	name: string
	age: int

    if age < 18 {
        responsible: string
    }
}
```

But `cue vet ` returns: `person2: field "responsible" not allowed in closed struct`.

It seems, that [conditional fields](https://cuelang.org/docs/tutorials/tour/expressions/conditional/) only work with `cue eval`.

Is there a way to conditionally validate a struct?
